-- V1__Schema_Producao_Original.sql
-- Este arquivo representa o estado ATUAL da produção de 2025.
-- O Flyway vai ignorar este arquivo na produção (Baseline), mas rodará em bancos novos.

CREATE TABLE public.caixas (
    id_caixa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conferido_crediario numeric(12,2),
    conferido_credito numeric(12,2),
    conferido_debito numeric(12,2),
    conferido_dinheiro numeric(12,2),
    conferido_pix numeric(12,2),
    data_abertura timestamp(6) without time zone NOT NULL,
    data_fechamento timestamp(6) without time zone,
    observacoes character varying(500),
    quebra_de_caixa numeric(12,2),
    saldo_inicial numeric(12,2) NOT NULL,
    sistema_total_vendas numeric(12,2),
    status character varying(20) NOT NULL,
    id_funcionario bigint NOT NULL
);

CREATE TABLE public.categorias (
    id_categoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL UNIQUE
);

CREATE TABLE public.clientes (
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    cpf character varying(11) NOT NULL UNIQUE,
    data_nascimento date NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    login character varying(255) NOT NULL UNIQUE,
    nome_completo character varying(255) NOT NULL,
    senha_criptografada character varying(255) NOT NULL,
    telefone character varying(15)
);

CREATE TABLE public.funcionarios (
    id_funcionario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    cargo character varying(30) NOT NULL,
    cpf character varying(11) NOT NULL UNIQUE,
    data_nascimento date NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    login character varying(255) NOT NULL UNIQUE,
    nome_completo character varying(255) NOT NULL,
    nome_registro character varying(255) NOT NULL,
    senha_criptografada character varying(255) NOT NULL,
    telefone character varying(15) NOT NULL
);

-- Tabela antiga de produtos
CREATE TABLE public.produtos (
    id_produto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo boolean NOT NULL,
    descricao character varying(500) NOT NULL,
    nome character varying(255) NOT NULL UNIQUE,
    quantidade_estoque integer NOT NULL,
    quantidade_minima integer NOT NULL,
    valor_custo numeric(12,2) NOT NULL,
    valor_venda numeric(12,2) NOT NULL,
    id_categoria bigint NOT NULL
);

CREATE TABLE public.venda (
    id_venda bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda timestamp(6) without time zone NOT NULL,
    metodo_pagamento character varying(50) NOT NULL,
    observacoes character varying(255),
    status_venda character varying(20) NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    id_caixa bigint NOT NULL,
    id_cliente bigint NOT NULL,
    id_funcionario bigint NOT NULL
);

CREATE TABLE public.venda_item (
    id_venda_item bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preco_unitario numeric(12,2) NOT NULL,
    quantidade integer NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    id_produto bigint NOT NULL,
    id_venda bigint NOT NULL
);

-- Foreign Keys Originais
ALTER TABLE public.caixas ADD CONSTRAINT fkgro3e04cecw1eddj72qrfq1k5 FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario);
ALTER TABLE public.produtos ADD CONSTRAINT fkbq4e9crnlcsvm7ehu147wuavt FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria);
ALTER TABLE public.venda ADD CONSTRAINT fk77eapuafidk1ulavs02jn3xqi FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente);
ALTER TABLE public.venda ADD CONSTRAINT fkj7pgld3pil4prr7qlqxfcnmcf FOREIGN KEY (id_caixa) REFERENCES public.caixas(id_caixa);
ALTER TABLE public.venda ADD CONSTRAINT fkjdgiq5om0dlosn0m8ha1xuf88 FOREIGN KEY (id_funcionario) REFERENCES public.funcionarios(id_funcionario);
ALTER TABLE public.venda_item ADD CONSTRAINT fkonswobk5kr885si08i8e94shl FOREIGN KEY (id_produto) REFERENCES public.produtos(id_produto);
ALTER TABLE public.venda_item ADD CONSTRAINT fk1u3c2afiyu4xrcgs0n76fwefa FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda);