-- ARQUIVO: V1__Estrutura_Base.sql
-- Baseado no seu DUMP atual. O Flyway vai ignorar a execução deste arquivo (Baseline),
-- mas ele serve de documentação do estado inicial.

CREATE TABLE IF NOT EXISTS public.caixas (
    id_caixa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_funcionario bigint NOT NULL,
    data_abertura timestamp(6) without time zone NOT NULL,
    data_fechamento timestamp(6) without time zone,
    saldo_inicial numeric(12,2) NOT NULL,
    quebra_de_caixa numeric(12,2),
    status character varying(20) NOT NULL,
    observacoes character varying(500),
    -- Campos extras do seu dump
    conferido_crediario numeric(12,2),
    conferido_credito numeric(12,2),
    conferido_debito numeric(12,2),
    conferido_dinheiro numeric(12,2),
    conferido_pix numeric(12,2),
    sistema_total_vendas numeric(12,2)
);

CREATE TABLE IF NOT EXISTS public.categorias (
    id_categoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.unidade (
    id_unidade bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia character varying(255) NOT NULL,
    razao_social character varying(255),
    documento_numero character varying(255) NOT NULL UNIQUE,
    tipo_documento character varying(255),
    inscricao_estadual character varying(255),
    telefone character varying(255),
    email_contato character varying(255),
    cep character varying(255),
    logradouro character varying(255),
    numero character varying(255),
    bairro character varying(255),
    cidade character varying(255),
    uf character varying(255),
    complemento character varying(255),
    grupo_economico_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.perfil_acesso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL UNIQUE,
    descricao character varying(255),
    tipo character varying(255)
);

CREATE TABLE IF NOT EXISTS public.funcionarios (
    id_funcionario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id bigint NOT NULL,
    perfil_acesso_id bigint NOT NULL,
    nome_completo character varying(255) NOT NULL,
    nome_registro character varying(255) NOT NULL,
    cpf character varying(11) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    login character varying(255) NOT NULL UNIQUE,
    senha_criptografada character varying(255) NOT NULL,
    telefone character varying(15) NOT NULL,
    cargo character varying(30) NOT NULL,
    dados_contratacao text,
    data_nascimento date NOT NULL,
    ativo boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.clientes (
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_origem_id bigint,
    funcionario_origem_id bigint UNIQUE,
    perfil_acesso_id bigint,
    nome_completo character varying(255) NOT NULL,
    cpf character varying(11) UNIQUE,
    email character varying(255) UNIQUE,
    login character varying(255) UNIQUE,
    senha_criptografada character varying(255) NOT NULL,
    telefone character varying(15),
    data_nascimento date NOT NULL,
    limite_credito numeric(12,2),
    bloqueado_fiado boolean NOT NULL,
    ativo boolean NOT NULL,
    assinatura_digital_url character varying(255),
    termo_aceito_versao_id integer
);

-- ESTAS TABELAS SERÃO REMOVIDAS/ALTERADAS NA V2
CREATE TABLE IF NOT EXISTS public.produtos (
    id_produto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria bigint NOT NULL,
    nome character varying(255) NOT NULL UNIQUE,
    descricao character varying(500) NOT NULL,
    valor_custo numeric(12,2) NOT NULL,
    valor_venda numeric(12,2) NOT NULL,
    quantidade_estoque integer NOT NULL,
    quantidade_minima integer NOT NULL,
    ativo boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.venda (
    id_venda bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_funcionario bigint NOT NULL,
    id_cliente bigint NOT NULL,
    id_caixa bigint NOT NULL,
    data_venda timestamp(6) without time zone NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    metodo_pagamento character varying(50) NOT NULL,
    status_venda character varying(20) NOT NULL,
    observacoes character varying(255)
);

CREATE TABLE IF NOT EXISTS public.venda_item (
    id_venda_item bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda bigint NOT NULL,
    id_produto bigint NOT NULL,
    quantidade integer NOT NULL,
    preco_unitario numeric(12,2) NOT NULL,
    subtotal numeric(12,2) NOT NULL
);

-- Constraints básicas para evitar erros se o Flyway tentar validar
ALTER TABLE ONLY public.funcionarios DROP CONSTRAINT IF EXISTS fk_func_unidade;
ALTER TABLE ONLY public.funcionarios ADD CONSTRAINT fk_func_unidade FOREIGN KEY (unidade_id) REFERENCES public.unidade(id_unidade);