-- V2__Atualizacao_Completa_pt3_Dev.sql - parte 1 a 3

-- 1. CRIAR AS TABELAS NOVAS QUE FALTAM NA PRODUÇÃO (Unidade e Perfil)
CREATE TABLE public.unidade (
    id_unidade bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_economico_id bigint NOT NULL,
    bairro character varying(255),
    cep character varying(255),
    cidade character varying(255),
    complemento character varying(255),
    documento_numero character varying(255) NOT NULL UNIQUE,
    email_contato character varying(255),
    inscricao_estadual character varying(255),
    logradouro character varying(255),
    nome_fantasia character varying(255) NOT NULL,
    numero character varying(255),
    razao_social character varying(255),
    telefone character varying(255),
    tipo_documento character varying(255),
    uf character varying(255)
);

CREATE TABLE public.perfil_acesso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255),
    nome character varying(255) NOT NULL UNIQUE,
    tipo character varying(255)
);

-- 2. ATUALIZAR TABELAS EXISTENTES (Funcionarios e Clientes) COM NOVAS COLUNAS
-- Adicionar colunas em Clientes
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS bloqueado_fiado boolean DEFAULT false;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS limite_credito numeric(12,2);
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS termo_aceito_versao_id integer;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS assinatura_digital_url character varying(255);
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS funcionario_origem_id bigint;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS perfil_acesso_id bigint;
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS unidade_origem_id bigint;

-- Adicionar colunas em Funcionarios
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS dados_contratacao text;
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS perfil_acesso_id bigint;
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS unidade_id bigint;

-- Criar as Foreign Keys para os novos campos
ALTER TABLE public.clientes ADD CONSTRAINT fk_cli_func FOREIGN KEY (funcionario_origem_id) REFERENCES public.funcionarios(id_funcionario);
ALTER TABLE public.clientes ADD CONSTRAINT fk_cli_perfil FOREIGN KEY (perfil_acesso_id) REFERENCES public.perfil_acesso(id);
ALTER TABLE public.clientes ADD CONSTRAINT fk_cli_unidade FOREIGN KEY (unidade_origem_id) REFERENCES public.unidade(id_unidade);

ALTER TABLE public.funcionarios ADD CONSTRAINT fk_func_perfil FOREIGN KEY (perfil_acesso_id) REFERENCES public.perfil_acesso(id);
ALTER TABLE public.funcionarios ADD CONSTRAINT fk_func_unidade FOREIGN KEY (unidade_id) REFERENCES public.unidade(id_unidade);


-- 3. REFATORAÇÃO DE PRODUTOS (Cuidado: Dados antigos de produtos serão removidos)

-- Limpar itens de venda (histórico) pois a referência do produto vai mudar
DELETE FROM public.venda_item;

-- Remover tabela antiga
DROP TABLE IF EXISTS public.produtos CASCADE;

-- Criar nova estrutura Pai/Filho
CREATE TABLE public.produtos_pai (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_generico character varying(200) NOT NULL,
    marca character varying(100),
    descricao text,
    ncm character varying(8) NOT NULL,
    ativo boolean DEFAULT true,
    categoria_id bigint NOT NULL,
    CONSTRAINT fk_pai_categoria FOREIGN KEY (categoria_id) REFERENCES public.categorias(id_categoria)
);

CREATE TABLE public.produtos_variacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_variacao character varying(100),
    nome_completo_concatenado character varying(255),
    codigo_barras character varying(50) UNIQUE,
    sku character varying(100) UNIQUE,
    preco_custo numeric(19,2) NOT NULL,
    preco_venda numeric(19,2) NOT NULL,
    ativo boolean DEFAULT true,
    produto_pai_id bigint NOT NULL,
    CONSTRAINT fk_var_pai FOREIGN KEY (produto_pai_id) REFERENCES public.produtos_pai(id)
);

CREATE TABLE public.estoque_saldos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade_atual integer DEFAULT 0 NOT NULL,
    quantidade_minima integer DEFAULT 5,
    unidade_id bigint NOT NULL,
    produto_variacao_id bigint NOT NULL,
    CONSTRAINT uk_estoque_unidade_produto UNIQUE (unidade_id, produto_variacao_id),
    CONSTRAINT fk_estoque_unidade FOREIGN KEY (unidade_id) REFERENCES public.unidade(id_unidade),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_variacao_id) REFERENCES public.produtos_variacoes(id)
);

-- 4. AJUSTAR VENDA_ITEM PARA A NOVA ESTRUTURA
ALTER TABLE public.venda_item DROP COLUMN IF EXISTS id_produto;
ALTER TABLE public.venda_item ADD COLUMN id_produto_variacao bigint;
ALTER TABLE public.venda_item ADD CONSTRAINT fk_item_produto_variacao FOREIGN KEY (id_produto_variacao) REFERENCES public.produtos_variacoes(id);

-- 5. AJUSTES FINAIS
ALTER TABLE public.categorias ADD COLUMN IF NOT EXISTS nome_normalizado character varying(255);
UPDATE public.categorias SET nome_normalizado = UPPER(nome) WHERE nome_normalizado IS NULL;
ALTER TABLE public.categorias ADD CONSTRAINT uk_categorias_nome_normalizado UNIQUE (nome_normalizado);