-- ARQUIVO: V2__Refatoracao_Produtos.sql

-- 1. LIMPEZA DE DADOS INCOMPATÍVEIS
-- Precisamos limpar os itens de venda pois eles apontam para produtos que deixarão de existir.
-- O cabeçalho da venda (financeiro) será mantido, mas o detalhe do item será perdido nesta migração.
DELETE FROM public.venda_item;

-- Remove a constraint antiga de produto
ALTER TABLE public.venda_item DROP CONSTRAINT IF EXISTS fkonswobk5kr885si08i8e94shl;

-- Remove a tabela antiga de produtos
DROP TABLE IF EXISTS public.produtos CASCADE;


-- 2. CRIAÇÃO DAS NOVAS TABELAS (Arquitetura Pai/Filho)

CREATE TABLE public.produtos_pai (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_generico character varying(200) NOT NULL,
    marca character varying(100),
    descricao text,
    ncm character varying(8) NOT NULL,
    ativo boolean DEFAULT true,
    categoria_id bigint NOT NULL,
    CONSTRAINT fk_pai_categoria FOREIGN KEY (categoria_id) REFERENCES public.categorias(id_categoria)
);

CREATE TABLE public.produtos_variacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_variacao character varying(100),
    nome_completo_concatenado character varying(255),
    codigo_barras character varying(50) UNIQUE,
    sku character varying(100) UNIQUE,
    preco_custo numeric(19,2) NOT NULL,
    preco_venda numeric(19,2) NOT NULL,
    ativo boolean DEFAULT true,
    produto_pai_id bigint NOT NULL,
    CONSTRAINT fk_var_pai FOREIGN KEY (produto_pai_id) REFERENCES public.produtos_pai(id)
);

CREATE TABLE public.estoque_saldos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade_atual integer DEFAULT 0 NOT NULL,
    quantidade_minima integer DEFAULT 5,
    unidade_id bigint NOT NULL,
    produto_variacao_id bigint NOT NULL,
    CONSTRAINT uk_estoque_unidade_produto UNIQUE (unidade_id, produto_variacao_id),
    CONSTRAINT fk_estoque_unidade FOREIGN KEY (unidade_id) REFERENCES public.unidade(id_unidade),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_variacao_id) REFERENCES public.produtos_variacoes(id)
);


-- 3. ADAPTAÇÃO DA TABELA DE ITENS DE VENDA
-- Remove a coluna antiga id_produto e adiciona a nova id_produto_variacao

ALTER TABLE public.venda_item DROP COLUMN IF EXISTS id_produto;

ALTER TABLE public.venda_item ADD COLUMN id_produto_variacao bigint;

-- Como limpamos a tabela no passo 1, podemos definir como NOT NULL agora?
-- Sim, pois a tabela está vazia. Se não limpássemos, daria erro.
-- Mas vamos deixar nullable primeiro, atualizar e depois travar, por segurança.
ALTER TABLE public.venda_item ALTER COLUMN id_produto_variacao SET NOT NULL;

ALTER TABLE public.venda_item
ADD CONSTRAINT fk_item_produto_variacao
FOREIGN KEY (id_produto_variacao) REFERENCES public.produtos_variacoes(id);

-- 4. AJUSTES FINAIS EM CATEGORIAS
-- Adicionar coluna nome_normalizado se não existir (usado no novo código)
ALTER TABLE public.categorias ADD COLUMN IF NOT EXISTS nome_normalizado character varying(255);
-- Atualiza as categorias existentes para ter nome normalizado
UPDATE public.categorias SET nome_normalizado = UPPER(nome) WHERE nome_normalizado IS NULL;
ALTER TABLE public.categorias ADD CONSTRAINT uk_categorias_nome_normalizado UNIQUE (nome_normalizado);