-- V3__Motor_Descontos.sql

-- Tabela de Cupons (Vouchers)
CREATE TABLE public.marketing_vouchers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(50) NOT NULL UNIQUE, -- Ex: "NATAL10"
    tipo character varying(20) NOT NULL, -- "PERCENTUAL" ou "FIXO"
    valor numeric(12,2) NOT NULL,
    quantidade_disponivel integer NOT NULL DEFAULT 0,
    validade_inicio timestamp without time zone,
    validade_fim timestamp without time zone,
    ativo boolean DEFAULT true,
    acumulativo boolean DEFAULT false -- Se true, pode somar com outros descontos
);

-- Tabela de Descontos aplicados em Vendas
CREATE TABLE public.venda_descontos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id bigint NOT NULL,
    origem character varying(20) NOT NULL, -- "VOUCHER" ou "MANUAL"
    codigo_referencia character varying(50), -- Código do voucher ou identificação do desconto manual
    valor_desconto_aplicado numeric(12,2) NOT NULL,
    CONSTRAINT fk_desconto_venda FOREIGN KEY (venda_id) REFERENCES public.venda(id_venda)
);

-- Modificação na tabela de Vendas para incluir valor bruto
ALTER TABLE public.venda ADD COLUMN valor_bruto numeric(12,2) DEFAULT 0;
-- (O campo valor_total já existe e será usado como valor líquido final)