-- V4__Controle_Caixa_Avancado.sql

-- Tabela de Movimentações de Caixa (Sangrias e Suprimentos)
CREATE TABLE public.caixa_movimentacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caixa bigint NOT NULL,
    tipo character varying(20) NOT NULL, -- 'SANGRIA' ou 'SUPRIMENTO'
    valor numeric(12,2) NOT NULL,
    motivo character varying(255) NOT NULL,
    data_hora timestamp without time zone DEFAULT NOW(),
    id_usuario_autorizador bigint, -- Funcionário que autorizou a movimentação
    CONSTRAINT fk_movimentacao_caixa FOREIGN KEY (id_caixa) REFERENCES public.caixas(id_caixa),
    CONSTRAINT fk_movimentacao_autorizador FOREIGN KEY (id_usuario_autorizador) REFERENCES public.funcionarios(id_funcionario)
);

-- Tabela de Pagamentos por Venda (para múltiplas formas de pagamento)
CREATE TABLE public.venda_pagamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda bigint NOT NULL,
    id_caixa bigint NOT NULL, -- Caixa onde o pagamento foi registrado
    forma_pagamento character varying(30) NOT NULL, -- 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX', etc.
    valor_pago numeric(12,2) NOT NULL, -- Quanto o cliente pagou com essa forma (Ex: 50.00)
    troco_gerado numeric(12,2) DEFAULT 0, -- Quanto foi devolvido ao cliente (Ex: 5.00)
    valor_liquido numeric(12,2) NOT NULL, -- Quanto efetivamente entrou no caixa (Ex: 45.00)
    CONSTRAINT fk_pagamento_venda FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda),
    CONSTRAINT fk_pagamento_caixa FOREIGN KEY (id_caixa) REFERENCES public.caixas(id_caixa)
);

-- Modificação na tabela de Vendas para incluir campo de troco total
ALTER TABLE public.venda ADD COLUMN troco_total numeric(12,2) DEFAULT 0;