-- V5__Modulo_Crediario.sql

-- Tabela Mestre da Dívida (Contrato)
CREATE TABLE public.contas_receber (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda bigint NOT NULL,
    id_cliente bigint NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    quantidade_parcelas integer NOT NULL,
    status character varying(20) NOT NULL, -- 'ABERTA', 'QUITADA'
    data_criacao timestamp without time zone DEFAULT NOW(),
    CONSTRAINT fk_cr_venda FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda),
    CONSTRAINT fk_cr_cliente FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente)
);

-- Tabela de Parcelas (Boletos)
CREATE TABLE public.parcelas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conta_receber bigint NOT NULL,
    numero_parcela integer NOT NULL, -- 1, 2, 3...
    valor_original numeric(12,2) NOT NULL,
    valor_pago numeric(12,2) DEFAULT 0,
    data_vencimento date NOT NULL,
    data_pagamento timestamp without time zone,
    status character varying(20) NOT NULL, -- 'PENDENTE', 'PAGA', 'ATRASADA'
    CONSTRAINT fk_parcela_conta FOREIGN KEY (id_conta_receber) REFERENCES public.contas_receber(id)
);