-- V6__Seguranca_Crediario_Evidencias.sql

-- Tabela para Assinaturas e Fotos (Evidências da Venda)
-- Usamos TEXT para base64 pois pode ser uma string muito longa
CREATE TABLE public.venda_evidencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda bigint NOT NULL,
    assinatura_base64 text, -- Assinatura digital do cliente/funcionário
    foto_comprovante_base64 text, -- Foto opcional (ex: documento ou rosto)
    data_registro timestamp without time zone DEFAULT NOW(),
    CONSTRAINT fk_evidencia_venda FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda)
);

-- Atualizar Funcionário (Controle Financeiro e Segurança)
ALTER TABLE public.funcionarios
ADD COLUMN pin_hash character varying(255), -- Senha numérica criptografada (4 a 6 dígitos)
ADD COLUMN limite_crediario numeric(12,2) DEFAULT 0.00, -- Limite para compra interna
ADD COLUMN valor_comissao_acumulado numeric(12,2) DEFAULT 0.00; -- Saldo de comissão a receber

-- Atualizar Cliente (Limite para Crediário Externo)
ALTER TABLE public.clientes
ADD COLUMN limite_credito numeric(12,2) DEFAULT 0.00;

// Atualizar Venda (Valor da Comissão para o Funcionário)
ALTER TABLE public.venda
ADD COLUMN valor_comissao numeric(12,2) DEFAULT 0.00;