-- V6__Seguranca_Crediario_Evidencias.sql

-- Tabela para Assinaturas e Fotos (Evidências da Venda)
CREATE TABLE IF NOT EXISTS public.venda_evidencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda bigint NOT NULL,
    assinatura_base64 text, -- Assinatura do cliente em base64 (pode ser uma imagem ou um desenho feito na tela)
    foto_comprovante_base64 text, -- Foto do comprovante de pagamento (pode ser boleto pago, comprovante de transferência, etc.)
    data_registro timestamp without time zone DEFAULT NOW(),
    CONSTRAINT fk_evidencia_venda FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda)
);

-- Atualizar Funcionário (Controle Financeiro e Segurança)
ALTER TABLE public.funcionarios
ADD COLUMN IF NOT EXISTS pin_hash character varying(255), -- Hash do PIN para acesso ao módulo de crediário
ADD COLUMN IF NOT EXISTS limite_crediario numeric(12,2) DEFAULT 0.00, -- Limite para concessão de crédito
ADD COLUMN IF NOT EXISTS valor_comissao_acumulado numeric(12,2) DEFAULT 0.00, -- Acúmulo de comissão para controle interno
ADD COLUMN IF NOT EXISTS status_crediario character varying(20) DEFAULT 'ATIVO'; -- Status para controle de acesso ao módulo de crediário (ATIVO, SUSPENSO)

-- Atualizar Cliente (Limite para Crediário Externo)
ALTER TABLE public.clientes
ADD COLUMN IF NOT EXISTS limite_credito numeric(12,2) DEFAULT 0.00;

-- Atualizar Venda (Valor da Comissão para o Funcionário)
-- (Corrigido de // para --)
ALTER TABLE public.venda
ADD COLUMN IF NOT EXISTS valor_comissao numeric(12,2) DEFAULT 0.00;